source("simulation_1.R")
library(EnvCpt)
library(changepoint)
set.seed(1)

vardata<- simulation_var(2000)
jpeg("simulation_plots/variance_sim.jpg")
plot(vardata[[1]])
dev.off()

varmodel_PELT <- cpt.var(vardata[[1]],method = "PELT")
jpeg("PELT_plots/variance_PELT.jpg")
plot(varmodel_PELT)
dev.off()
jpeg("Truecpt_PELT/variance.jpg")
plot(varmodel_PELT)
abline(v = vardata[[2]],col = 'blue')
dev.off()

varmodel_binseg <- cpt.var(vardata[[1]],method = "BinSeg")
jpeg("BinSeg_plots/variance_BinSeg.jpg")
plot(varmodel_binseg)
dev.off()
jpeg("Truecpt_BinSeg/variance.jpg")
plot(varmodel_binseg)
abline(v = vardata[[2]],col = 'blue')
dev.off()

meandata<- simulation_mean(2000)
jpeg("simulation_plots/mean_sim.jpg")
plot(meandata[[1]])
dev.off()

meanmodel_PELT <- cpt.mean(meandata[[1]],method = "PELT")
jpeg("PELT_plots/mean_PELT.jpg")
plot(meanmodel_PELT)
dev.off()
jpeg("Truecpt_PELT/mean.jpg")
plot(meanmodel_PELT)
abline(v = meandata[[2]],col = 'blue')
dev.off()

meanmodel_binseg <- cpt.mean(meandata[[1]],method = "BinSeg")
jpeg("BinSeg_plots/mean_BinSeg.jpg")
plot(meanmodel_binseg)
dev.off()
jpeg("Truecpt_BinSeg/mean.jpg")
plot(meanmodel_binseg)
abline(v = meandata[[2]],col = 'blue')
dev.off()

meanvardata<- simulation_meanvar(2000)
jpeg("simulation_plots/meanvariance_sim.jpg")
plot(meanvardata[[1]])
dev.off()

meanvarmodel_PELT <- cpt.meanvar(meanvardata[[1]],method = "PELT")
jpeg("PELT_plots/meanvariance_PELT.jpg")
plot(meanvarmodel_PELT)
dev.off()
jpeg("Truecpt_PELT/meanvariance.jpg")
plot(meanvarmodel_PELT)
abline(v = meanvardata[[2]],col = 'blue')
dev.off()

meanvarmodel_binseg <- cpt.meanvar(meanvardata[[1]],method = "BinSeg")
jpeg("BinSeg_plots/meanvariance_BinSeg.jpg")
plot(meanvarmodel_binseg)
dev.off()
jpeg("Truecpt_BinSeg/meanvariance.jpg")
plot(meanvarmodel_binseg)
abline(v = meanvardata[[2]],col = 'blue')
dev.off()

trenddata <- simulation_trend(2000)
jpeg("simulation_plots/trend_sim.jpg")
plot(trenddata[[1]])
dev.off()

trendmodel <- envcpt(trenddata[[1]],model="trendcpt")

plot(trendmodel)
trendmodel
trendmodel$trendcpt
jpeg("Truecpt_PELT/trend.jpg")
plot(trenddata[[1]])
abline(v = trenddata[[2]],col="green")
abline(v = cpts(trendmodel$trendcpt)
,col="red")
dev.off()
